"""Runs the Sprint 2 administrator demonstration against an in-memory database and writes the
real request/response evidence to DEMO_EVIDENCE.md (tokens are redacted).

Usage:   JWT_SECRET=<any 16+ chars> python -m scripts.demo
"""
import json
import os
import sys
from pathlib import Path

os.environ.setdefault("BCRYPT_ROUNDS", "4")

from fastapi.testclient import TestClient  # noqa: E402
from sqlalchemy.orm import sessionmaker  # noqa: E402

from app.database import Base, create_sqlite_memory_engine, get_db  # noqa: E402
from app.main import app  # noqa: E402
from app.models import User  # noqa: E402
from app.security import hash_password  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "DEMO_EVIDENCE.md"
DEMO_PASSWORD = "Demo-Password-1"


def main() -> None:
    if len(os.getenv("JWT_SECRET", "")) < 16:
        sys.exit("Set JWT_SECRET (16+ characters) first, e.g.  JWT_SECRET=demo-secret-0123456789 python -m scripts.demo")

    engine = create_sqlite_memory_engine()
    Base.metadata.create_all(engine)
    factory = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)
    with factory() as s:
        s.add(User(email="admin@example.com", password_hash=hash_password(DEMO_PASSWORD), full_name="Demo Admin", role="admin"))
        s.commit()

    def override():
        with factory() as s:
            yield s

    app.dependency_overrides[get_db] = override
    client = TestClient(app)
    lines = ["# Sprint 2 demonstration evidence", "", "_Generated by `python -m scripts.demo` (in-memory SQLite, tokens redacted)._", ""]
    state = {"token": None, "n": 0}

    def step(title, method, path, body=None, auth=True, shown_body=None):
        state["n"] += 1
        headers = {"Authorization": f"Bearer {state['token']}"} if auth and state["token"] else {}
        resp = client.request(method, path, json=body, headers=headers)
        payload = resp.json() if resp.content else None
        if isinstance(payload, dict) and "access_token" in payload:
            payload = {**payload, "access_token": "<redacted>"}
        lines.append(f"## {state['n']}. {title}")
        lines.append("")
        lines.append("```http")
        lines.append(f"{method} {path}" + ("\nAuthorization: Bearer <redacted>" if headers else ""))
        lines.append("```")
        shown = shown_body if shown_body is not None else body
        if shown is not None:
            lines.extend(["```json", json.dumps(shown, indent=2), "```"])
        lines.append(f"**Response {resp.status_code}**")
        if payload is not None:
            lines.extend(["```json", json.dumps(payload, indent=2, default=str), "```"])
        lines.append("")
        return resp

    login = step(
        "Administrator logs in", "POST", "/api/v1/auth/login",
        {"email": "admin@example.com", "password": DEMO_PASSWORD}, auth=False,
        shown_body={"email": "admin@example.com", "password": "<redacted>"},
    )
    state["token"] = login.json()["access_token"]

    step("Unauthenticated write is rejected", "POST", "/api/v1/admin/categories", {"name": "Nope", "slug": "nope"}, auth=False)
    root = step("Create a root category", "POST", "/api/v1/admin/categories", {"name": "Apparel", "slug": "apparel"}).json()
    child = step("Create a child category", "POST", "/api/v1/admin/categories", {"name": "Hoodies", "slug": "hoodies", "parent_id": root["id"]}).json()
    step("Cycle prevention: make the root a child of its own child", "PATCH", f"/api/v1/admin/categories/{root['id']}", {"parent_id": child["id"]})
    product = step("Create a draft product", "POST", "/api/v1/admin/products", {"category_id": child["id"], "name": "Classic Custom Hoodie", "slug": "classic-custom-hoodie", "description": "Heavyweight fleece hoodie.", "customization_type": "print", "specifications": {"material": "cotton blend", "weight_gsm": 320}}).json()
    pid = product["id"]
    step("Publishing without a SKU is rejected", "PATCH", f"/api/v1/admin/products/{pid}", {"status": "published"})
    variant = step("Create a variant (valid combination)", "POST", f"/api/v1/admin/products/{pid}/variants", {"option_values": {"color": "Black", "size": "M"}}).json()
    step("Add a SKU to that variant", "POST", f"/api/v1/admin/products/{pid}/skus", {"code": "HOOD-BLK-M", "price": "59.00", "stock_quantity": 40, "variant_id": variant["id"]})
    sku2 = step("Add a SKU by option values (variant created automatically)", "POST", f"/api/v1/admin/products/{pid}/skus", {"code": "HOOD-WHT-M", "price": "59.00", "stock_quantity": 0, "option_values": {"color": "White", "size": "M"}}).json()
    step("Duplicate SKU code (different case) is a clean client error", "POST", f"/api/v1/admin/products/{pid}/skus", {"code": "hood-blk-m", "price": "10.00", "option_values": {"color": "Black", "size": "L"}})
    step("Duplicate product slug is a clean client error", "POST", "/api/v1/admin/products", {"category_id": child["id"], "name": "Another", "slug": "classic-custom-hoodie"})
    step("Negative stock via update is rejected", "PATCH", f"/api/v1/admin/skus/{sku2['id']}", {"stock_delta": -1})
    step("Restock a SKU", "PATCH", f"/api/v1/admin/skus/{sku2['id']}", {"stock_delta": 15})
    step("Publish the product (now has active SKUs)", "PATCH", f"/api/v1/admin/products/{pid}", {"status": "published"})
    step("List administrative product records", "GET", "/api/v1/admin/products")
    step("Retrieve the category tree", "GET", "/api/v1/admin/categories")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
